#!/bin/bash

# 生成随机矿工名
WORKER_NAME="unmineable_worker_$(date +%s)_$RANDOM"

# 创建并启动一个新的 screen 会话，执行挖矿程序
screen -dmS xmrig_mining ./xmrig -a rx -o stratum+ssl://rx.unmineable.com:443 -u USDT:TGpiKru64ovzRMeBVTNgDDC5fakbDVU9Qk.${WORKER_NAME}#pblk-utjn -p x

# 输出通知
echo "XMRig 挖矿已在后台运行，并且在 screen 会话中运行！"
echo "你可以通过 'screen -r xmrig_mining' 来查看挖矿日志。"
